### ISSUE TITLE
Have you abandoned this repo?

### ISSUE THREAD

**Issue by alireza-ahmadi** [apollographql/apollo-server-tutorial#8]
I just want to know that have you abandoned this repo or you will update it in the future?
This repo uses old versions of **Apollo Stack** components and `fortunecookieapi.com` that has been used in the source code is expired.

Would be glad to submit a pull request for updating and making this repo runnable.

**Comment by unicodeveloper** [comment]
Thanks, @alireza-ahmadi Right now there are no plans to update this repo since it runs on Apollo Server 1.0. However, we are open to PRs to make it runnable again.
